server:
  http_listen_port: 3200
#  grpc_listen_port: 9195
# -- Log level. Can be set to trace, debug, info (default), warn, error, fatal, panic
#  log_level: debug

distributor:
  receivers:                           # this configuration will listen on all ports and protocols that tempo is capable of.
#    jaeger:                            # the receives all come from the OpenTelemetry collector.  more configuration information can
#      protocols:                       # be found there: https://github.com/open-telemetry/opentelemetry-collector/tree/main/receiver
#        thrift_http:                   #
#        grpc:                          # for a production deployment you should only enable the receivers you need!
#        thrift_binary:
#        thrift_compact:
#    zipkin:
    otlp:
      protocols:
        http:
           endpoint: "192.168.8.126:4318"
#          endpoint: "0.0.0.0:4328"
#        grpc:
#          endpoint: "0.0.0.0:4327"
#    opencensus:


    # -- Enable to log every received span to help debug ingestion or calculate span error distributions using the logs
#  log_received_spans:
#    enabled: true
#    include_all_attributes: true
#    filter_by_status_error: true


#ingester:
#  max_block_duration: 5m               # cut the headblock when this much time passes. this is being set for demo purposes and should probably be left alone normally

#compactor:
#  compaction:
#    block_retention: 1h                # overall Tempo trace retention. set for demo purposes

metrics_generator:
  registry:
    external_labels:
      source: tempo
#      cluster: linux-microservices
  storage:
    path: /tmp/tempo/generator/wal
    remote_write:
      - url: http://192.168.34.126:9090/api/v1/write
        send_exemplars: true

storage:
  trace:
    backend: local                     # backend configuration to use
    wal:
      path: /tmp/tempo/wal             # where to store the the wal locally
    local:
      path: /tmp/tempo/blocks

overrides:
  metrics_generator_processors: [service-graphs, span-metrics] # enables metrics generator
